### ISSUE TITLE
Phase-1-Fetch-Lab

### ISSUE THREAD

**Issue by JacobyJanoble** [learn-co-curriculum/phase-1-fetch-lab#5]
### Canvas Link

https://learning.flatironschool.com/courses/4999/assignments/165576?module_item_id=357381

### Concern

I have the code entered in correctly and have it verified to be correct but test 2 keeps failing.

Error Message:

"TypeError: Cannot read properties of undefined (reading 'then')"

Somebody else expressed to me that this was a problem for them as well.

**Comment by lizbur10** [comment]
Hi there! The issue here is that you aren't returning the fetch - see the Note near the bottom of the lesson, and the comment at the top of the index.js file. All you need to do is add the return keyword in front of fetch 😃
